import {
  StepBackwardOutlined, StepForwardOutlined, FastBackwardOutlined, FastForwardOutlined,
  ShrinkOutlined, ArrowsAltOutlined, DownOutlined, UpOutlined, LeftOutlined,
  RightOutlined, CaretUpOutlined, CaretDownOutlined, CaretLeftOutlined,
  CaretRightOutlined, UpCircleOutlined, DownCircleOutlined, LeftCircleOutlined,
  RightCircleOutlined, DoubleRightOutlined, DoubleLeftOutlined, VerticalLeftOutlined,
  VerticalRightOutlined, VerticalAlignTopOutlined, VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined, ForwardOutlined, BackwardOutlined, RollbackOutlined, 
  EnterOutlined, RetweetOutlined, SwapOutlined, SwapLeftOutlined, 
  SwapRightOutlined, ArrowUpOutlined, ArrowDownOutlined, ArrowLeftOutlined, 
  ArrowRightOutlined, PlayCircleOutlined, UpSquareOutlined, DownSquareOutlined,
  LeftSquareOutlined, RightSquareOutlined, LoginOutlined, LogoutOutlined,
  MenuFoldOutlined, MenuUnfoldOutlined, BorderBottomOutlined, BorderHorizontalOutlined, 
  BorderInnerOutlined, BorderOuterOutlined, BorderLeftOutlined, BorderRightOutlined,
  BorderTopOutlined, BorderVerticleOutlined, PicCenterOutlined, PicLeftOutlined,
  PicRightOutlined, RadiusBottomleftOutlined, RadiusBottomrightOutlined,
  RadiusUpleftOutlined, RadiusUprightOutlined, FullscreenOutlined, FullscreenExitOutlined,

  QuestionOutlined,
  QuestionCircleOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  PauseOutlined,
  PauseCircleOutlined,
  MinusOutlined,
  MinusCircleOutlined,
  PlusSquareOutlined,
  MinusSquareOutlined,
  InfoOutlined,
  InfoCircleOutlined,
  ExclamationOutlined,
  ExclamationCircleOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  CloseSquareOutlined,
  CheckOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  WarningOutlined,
  IssuesCloseOutlined,
  StopOutlined,

  EditOutlined,
  FormOutlined,
  CopyOutlined,
  ScissorOutlined,
  DeleteOutlined,
  SnippetsOutlined,
  DiffOutlined,
  HighlightOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  BgColorsOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  RedoOutlined,
  UndoOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  LineHeightOutlined,
  DashOutlined,
  SmallDashOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  DragOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  RadiusSettingOutlined,
  ColumnWidthOutlined,
  ColumnHeightOutlined,

  AreaChartOutlined,
  PieChartOutlined,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  RadarChartOutlined,
  HeatMapOutlined,
  FallOutlined,
  RiseOutlined,
  StockOutlined,
  BoxPlotOutlined,
  FundOutlined,
  SlidersOutlined,

  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  IeOutlined,
  ChromeOutlined,
  GithubOutlined,
  AliwangwangOutlined,
  DingdingOutlined,
  WeiboSquareOutlined,
  WeiboCircleOutlined,
  TaobaoCircleOutlined,
  Html5Outlined,
  WeiboOutlined,
  TwitterOutlined,
  WechatOutlined,
  YoutubeOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  SkypeOutlined,
  QqOutlined,
  MediumWorkmarkOutlined,
  GitlabOutlined,
  MediumOutlined,
  LinkedinOutlined,
  GooglePlusOutlined,
  DropboxOutlined,
  FacebookOutlined,
  CodepenOutlined,
  CodeSandboxOutlined,
  AmazonOutlined,
  GoogleOutlined,
  CodepenCircleOutlined,
  AlipayOutlined,
  AntDesignOutlined,
  AntCloudOutlined,
  AliyunOutlined,
  ZhihuOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  DribbbleOutlined,
  DribbbleSquareOutlined,
  InstagramOutlined,
  YuqueOutlined,
  AlibabaOutlined,
  YahooOutlined,
  RedditOutlined,
  SketchOutlined,



  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AudioOutlined,
  AudioMutedOutlined,
  AuditOutlined,
  BankOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BorderOutlined,
  BorderlessTableOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CarryOutOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DingtalkOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DownloadOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  FolderViewOutlined,
  ForkOutlined,
  FormatPainterOutlined,
  FrownOutlined,
  FunctionOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GlobalOutlined,
  GoldOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HistoryOutlined,
  HomeOutlined,
  HourglassOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LikeOutlined,
  LineOutlined,
  LinkOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MehOutlined,
  MenuOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlaySquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  ReloadOutlined,
  RestOutlined,
  RobotOutlined,
  RocketOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SisternodeOutlined,
  SkinOutlined,
  SmileOutlined,
  SolutionOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  SubnodeOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WomanOutlined,
} from '@ant-design/icons'



const iconObj = (style: any):any => {
  return {
    AccountBookOutlined: <AccountBookOutlined style={style} />,
    AimOutlined: <AimOutlined style={style} />,
    AlertOutlined: <AlertOutlined style={style} />,
    ApartmentOutlined: <ApartmentOutlined style={style} />,
    ApiOutlined: <ApiOutlined style={style} />,
    AppstoreAddOutlined: <AppstoreAddOutlined style={style} />,
    AppstoreOutlined: <AppstoreOutlined style={style} />,
    AudioOutlined: <AudioOutlined style={style} />,
    AudioMutedOutlined: <AudioMutedOutlined style={style} />,
    AuditOutlined: <AuditOutlined style={style} />,
    BankOutlined: <BankOutlined style={style} />,
    BarcodeOutlined: <BarcodeOutlined style={style} />,
    BarsOutlined: <BarsOutlined style={style} />,
    BellOutlined: <BellOutlined style={style} />,
    BlockOutlined: <BlockOutlined style={style} />,
    BookOutlined: <BookOutlined style={style} />,
    BorderOutlined: <BorderOutlined style={style} />,
    BorderlessTableOutlined: <BorderlessTableOutlined style={style} />,
    BranchesOutlined: <BranchesOutlined style={style} />,
    BugOutlined: <BugOutlined style={style} />,
    BuildOutlined: <BuildOutlined style={style} />,
    BulbOutlined: <BulbOutlined style={style} />,
    CalculatorOutlined: <CalculatorOutlined style={style} />,
    CalendarOutlined: <CalendarOutlined style={style} />,
    CameraOutlined: <CameraOutlined style={style} />,
    CarOutlined: <CarOutlined style={style} />,
    CarryOutOutlined: <CarryOutOutlined style={style} />,
    CiCircleOutlined: <CiCircleOutlined style={style} />,
    CiOutlined: <CiOutlined style={style} />,
    ClearOutlined: <ClearOutlined style={style} />,
    CloudDownloadOutlined: <CloudDownloadOutlined style={style} />,
    CloudOutlined: <CloudOutlined style={style} />,
    CloudServerOutlined: <CloudServerOutlined style={style} />,
    CloudSyncOutlined: <CloudSyncOutlined style={style} />,
    CloudUploadOutlined: <CloudUploadOutlined style={style} />,
    ClusterOutlined: <ClusterOutlined style={style} />,
    CodeOutlined: <CodeOutlined style={style} />,
    CoffeeOutlined: <CoffeeOutlined style={style} />,
    CommentOutlined: <CommentOutlined style={style} />,
    CompassOutlined: <CompassOutlined style={style} />,
    CompressOutlined: <CompressOutlined style={style} />,
    ConsoleSqlOutlined: <ConsoleSqlOutlined style={style} />,
    ContactsOutlined: <ContactsOutlined style={style} />,
    ContainerOutlined: <ContainerOutlined style={style} />,
    ControlOutlined: <ControlOutlined style={style} />,
    CopyrightOutlined: <CopyrightOutlined style={style} />,
    CreditCardOutlined: <CreditCardOutlined style={style} />,
    CrownOutlined: <CrownOutlined style={style} />,
    CustomerServiceOutlined: <CustomerServiceOutlined style={style} />,
    DashboardOutlined: <DashboardOutlined style={style} />,
    DatabaseOutlined: <DatabaseOutlined style={style} />,
    DeleteColumnOutlined: <DeleteColumnOutlined style={style} />,
    DeleteRowOutlined: <DeleteRowOutlined style={style} />,
    DeliveredProcedureOutlined: <DeliveredProcedureOutlined style={style} />,
    DeploymentUnitOutlined: <DeploymentUnitOutlined style={style} />,
    DesktopOutlined: <DesktopOutlined style={style} />,
    DingtalkOutlined: <DingtalkOutlined style={style} />,
    DisconnectOutlined: <DisconnectOutlined style={style} />,
    DislikeOutlined: <DislikeOutlined style={style} />,
    DollarCircleOutlined: <DollarCircleOutlined style={style} />,
    DollarOutlined: <DollarOutlined style={style} />,
    DownloadOutlined: <DownloadOutlined style={style} />,
    EllipsisOutlined: <EllipsisOutlined style={style} />,
    EnvironmentOutlined: <EnvironmentOutlined style={style} />,
    EuroCircleOutlined: <EuroCircleOutlined style={style} />,
    EuroOutlined: <EuroOutlined style={style} />,
    ExceptionOutlined: <ExceptionOutlined style={style} />,
    ExpandAltOutlined: <ExpandAltOutlined style={style} />,
    ExpandOutlined: <ExpandOutlined style={style} />,
    ExperimentOutlined: <ExperimentOutlined style={style} />,
    ExportOutlined: <ExportOutlined style={style} />,
    EyeOutlined: <EyeOutlined style={style} />,
    EyeInvisibleOutlined: <EyeInvisibleOutlined style={style} />,
    FieldBinaryOutlined: <FieldBinaryOutlined style={style} />,
    FieldNumberOutlined: <FieldNumberOutlined style={style} />,
    FieldStringOutlined: <FieldStringOutlined style={style} />,
    FieldTimeOutlined: <FieldTimeOutlined style={style} />,
    FileAddOutlined: <FileAddOutlined style={style} />,
    FileDoneOutlined: <FileDoneOutlined style={style} />,
    FileExcelOutlined: <FileExcelOutlined style={style} />,
    FileExclamationOutlined: <FileExclamationOutlined style={style} />,
    FileOutlined: <FileOutlined style={style} />,
    FileGifOutlined: <FileGifOutlined style={style} />,
    FileImageOutlined: <FileImageOutlined style={style} />,
    FileJpgOutlined: <FileJpgOutlined style={style} />,
    FileMarkdownOutlined: <FileMarkdownOutlined style={style} />,
    FilePdfOutlined: <FilePdfOutlined style={style} />,
    FilePptOutlined: <FilePptOutlined style={style} />,
    FileProtectOutlined: <FileProtectOutlined style={style} />,
    FileSearchOutlined: <FileSearchOutlined style={style} />,
    FileSyncOutlined: <FileSyncOutlined style={style} />,
    FileTextOutlined: <FileTextOutlined style={style} />,
    FileUnknownOutlined: <FileUnknownOutlined style={style} />,
    FileWordOutlined: <FileWordOutlined style={style} />,
    FileZipOutlined: <FileZipOutlined style={style} />,
    FilterOutlined: <FilterOutlined style={style} />,
    FireOutlined: <FireOutlined style={style} />,
    FlagOutlined: <FlagOutlined style={style} />,
    FolderAddOutlined: <FolderAddOutlined style={style} />,
    FolderOutlined: <FolderOutlined style={style} />,
    FolderOpenOutlined: <FolderOpenOutlined style={style} />,
    FolderViewOutlined: <FolderViewOutlined style={style} />,
    ForkOutlined: <ForkOutlined style={style} />,
    FormatPainterOutlined: <FormatPainterOutlined style={style} />,
    FrownOutlined: <FrownOutlined style={style} />,
    FunctionOutlined: <FunctionOutlined style={style} />,
    FundProjectionScreenOutlined: <FundProjectionScreenOutlined style={style} />,
    FundViewOutlined: <FundViewOutlined style={style} />,
    FunnelPlotOutlined: <FunnelPlotOutlined style={style} />,
    GatewayOutlined: <GatewayOutlined style={style} />,
    GifOutlined: <GifOutlined style={style} />,
    GiftOutlined: <GiftOutlined style={style} />,
    GlobalOutlined: <GlobalOutlined style={style} />,
    GoldOutlined: <GoldOutlined style={style} />,
    GroupOutlined: <GroupOutlined style={style} />,
    HddOutlined: <HddOutlined style={style} />,
    HeartOutlined: <HeartOutlined style={style} />,
    HistoryOutlined: <HistoryOutlined style={style} />,
    HomeOutlined: <HomeOutlined style={style} />,
    HourglassOutlined: <HourglassOutlined style={style} />,
    IdcardOutlined: <IdcardOutlined style={style} />,
    ImportOutlined: <ImportOutlined style={style} />,
    InboxOutlined: <InboxOutlined style={style} />,
    InsertRowAboveOutlined: <InsertRowAboveOutlined style={style} />,
    InsertRowBelowOutlined: <InsertRowBelowOutlined style={style} />,
    InsertRowLeftOutlined: <InsertRowLeftOutlined style={style} />,
    InsertRowRightOutlined: <InsertRowRightOutlined style={style} />,
    InsuranceOutlined: <InsuranceOutlined style={style} />,
    InteractionOutlined: <InteractionOutlined style={style} />,
    KeyOutlined: <KeyOutlined style={style} />,
    LaptopOutlined: <LaptopOutlined style={style} />,
    LayoutOutlined: <LayoutOutlined style={style} />,
    LikeOutlined: <LikeOutlined style={style} />,
    LineOutlined: <LineOutlined style={style} />,
    LinkOutlined: <LinkOutlined style={style} />,
    Loading3QuartersOutlined: <Loading3QuartersOutlined style={style} />,
    LoadingOutlined: <LoadingOutlined style={style} />,
    LockOutlined: <LockOutlined style={style} />,
    MacCommandOutlined: <MacCommandOutlined style={style} />,
    MailOutlined: <MailOutlined style={style} />,
    ManOutlined: <ManOutlined style={style} />,
    MedicineBoxOutlined: <MedicineBoxOutlined style={style} />,
    MehOutlined: <MehOutlined style={style} />,
    MenuOutlined: <MenuOutlined style={style} />,
    MergeCellsOutlined: <MergeCellsOutlined style={style} />,
    MessageOutlined: <MessageOutlined style={style} />,
    MobileOutlined: <MobileOutlined style={style} />,
    MoneyCollectOutlined: <MoneyCollectOutlined style={style} />,
    MonitorOutlined: <MonitorOutlined style={style} />,
    MoreOutlined: <MoreOutlined style={style} />,
    NodeCollapseOutlined: <NodeCollapseOutlined style={style} />,
    NodeExpandOutlined: <NodeExpandOutlined style={style} />,
    NodeIndexOutlined: <NodeIndexOutlined style={style} />,
    NotificationOutlined: <NotificationOutlined style={style} />,
    NumberOutlined: <NumberOutlined style={style} />,
    OneToOneOutlined: <OneToOneOutlined style={style} />,
    PaperClipOutlined: <PaperClipOutlined style={style} />,
    PartitionOutlined: <PartitionOutlined style={style} />,
    PayCircleOutlined: <PayCircleOutlined style={style} />,
    PercentageOutlined: <PercentageOutlined style={style} />,
    PhoneOutlined: <PhoneOutlined style={style} />,
    PictureOutlined: <PictureOutlined style={style} />,
    PlaySquareOutlined: <PlaySquareOutlined style={style} />,
    PoundCircleOutlined: <PoundCircleOutlined style={style} />,
    PoundOutlined: <PoundOutlined style={style} />,
    PoweroffOutlined: <PoweroffOutlined style={style} />,
    PrinterOutlined: <PrinterOutlined style={style} />,
    ProfileOutlined: <ProfileOutlined style={style} />,
    ProjectOutlined: <ProjectOutlined style={style} />,
    PropertySafetyOutlined: <PropertySafetyOutlined style={style} />,
    PullRequestOutlined: <PullRequestOutlined style={style} />,
    PushpinOutlined: <PushpinOutlined style={style} />,
    QrcodeOutlined: <QrcodeOutlined style={style} />,
    ReadOutlined: <ReadOutlined style={style} />,
    ReconciliationOutlined: <ReconciliationOutlined style={style} />,
    RedEnvelopeOutlined: <RedEnvelopeOutlined style={style} />,
    ReloadOutlined: <ReloadOutlined style={style} />,
    RestOutlined: <RestOutlined style={style} />,
    RobotOutlined: <RobotOutlined style={style} />,
    RocketOutlined: <RocketOutlined style={style} />,
    RotateLeftOutlined: <RotateLeftOutlined style={style} />,
    RotateRightOutlined: <RotateRightOutlined style={style} />,
    SafetyCertificateOutlined: <SafetyCertificateOutlined style={style} />,
    SafetyOutlined: <SafetyOutlined style={style} />,
    SaveOutlined: <SaveOutlined style={style} />,
    ScanOutlined: <ScanOutlined style={style} />,
    ScheduleOutlined: <ScheduleOutlined style={style} />,
    SearchOutlined: <SearchOutlined style={style} />,
    SecurityScanOutlined: <SecurityScanOutlined style={style} />,
    SelectOutlined: <SelectOutlined style={style} />,
    SendOutlined: <SendOutlined style={style} />,
    SettingOutlined: <SettingOutlined style={style} />,
    ShakeOutlined: <ShakeOutlined style={style} />,
    ShareAltOutlined: <ShareAltOutlined style={style} />,
    ShopOutlined: <ShopOutlined style={style} />,
    ShoppingCartOutlined: <ShoppingCartOutlined style={style} />,
    ShoppingOutlined: <ShoppingOutlined style={style} />,
    SisternodeOutlined: <SisternodeOutlined style={style} />,
    SkinOutlined: <SkinOutlined style={style} />,
    SmileOutlined: <SmileOutlined style={style} />,
    SolutionOutlined: <SolutionOutlined style={style} />,
    SoundOutlined: <SoundOutlined style={style} />,
    SplitCellsOutlined: <SplitCellsOutlined style={style} />,
    StarOutlined: <StarOutlined style={style} />,
    SubnodeOutlined: <SubnodeOutlined style={style} />,
    SwitcherOutlined: <SwitcherOutlined style={style} />,
    SyncOutlined: <SyncOutlined style={style} />,
    TableOutlined: <TableOutlined style={style} />,
    TabletOutlined: <TabletOutlined style={style} />,
    TagOutlined: <TagOutlined style={style} />,
    TagsOutlined: <TagsOutlined style={style} />,
    TeamOutlined: <TeamOutlined style={style} />,
    ThunderboltOutlined: <ThunderboltOutlined style={style} />,
    ToTopOutlined: <ToTopOutlined style={style} />,
    ToolOutlined: <ToolOutlined style={style} />,
    TrademarkCircleOutlined: <TrademarkCircleOutlined style={style} />,
    TrademarkOutlined: <TrademarkOutlined style={style} />,
    TransactionOutlined: <TransactionOutlined style={style} />,
    TranslationOutlined: <TranslationOutlined style={style} />,
    TrophyOutlined: <TrophyOutlined style={style} />,
    UngroupOutlined: <UngroupOutlined style={style} />,
    UnlockOutlined: <UnlockOutlined style={style} />,
    UploadOutlined: <UploadOutlined style={style} />,
    UsbOutlined: <UsbOutlined style={style} />,
    UserAddOutlined: <UserAddOutlined style={style} />,
    UserDeleteOutlined: <UserDeleteOutlined style={style} />,
    UserOutlined: <UserOutlined style={style} />,
    UserSwitchOutlined: <UserSwitchOutlined style={style} />,
    UsergroupAddOutlined: <UsergroupAddOutlined style={style} />,
    UsergroupDeleteOutlined: <UsergroupDeleteOutlined style={style} />,
    VerifiedOutlined: <VerifiedOutlined style={style} />,
    VideoCameraAddOutlined: <VideoCameraAddOutlined style={style} />,
    VideoCameraOutlined: <VideoCameraOutlined style={style} />,
    WalletOutlined: <WalletOutlined style={style} />,
    WhatsAppOutlined: <WhatsAppOutlined style={style} />,
    WifiOutlined: <WifiOutlined style={style} />,
    WomanOutlined: <WomanOutlined style={style} />,


    AndroidOutlined: <AndroidOutlined style={style} />,
    AppleOutlined: <AppleOutlined style={style} />,
    WindowsOutlined: <WindowsOutlined style={style} />,
    IeOutlined: <IeOutlined style={style} />,
    ChromeOutlined: <ChromeOutlined style={style} />,
    GithubOutlined: <GithubOutlined style={style} />,
    AliwangwangOutlined: <AliwangwangOutlined style={style} />,
    DingdingOutlined: <DingdingOutlined style={style} />,
    WeiboSquareOutlined: <WeiboSquareOutlined style={style} />,
    WeiboCircleOutlined: <WeiboCircleOutlined style={style} />,
    TaobaoCircleOutlined: <TaobaoCircleOutlined style={style} />,
    Html5Outlined: <Html5Outlined style={style} />,
    WeiboOutlined: <WeiboOutlined style={style} />,
    TwitterOutlined: <TwitterOutlined style={style} />,
    WechatOutlined: <WechatOutlined style={style} />,
    YoutubeOutlined: <YoutubeOutlined style={style} />,
    AlipayCircleOutlined: <AlipayCircleOutlined style={style} />,
    TaobaoOutlined: <TaobaoOutlined style={style} />,
    SkypeOutlined: <SkypeOutlined style={style} />,
    QqOutlined: <QqOutlined style={style} />,
    MediumWorkmarkOutlined: <MediumWorkmarkOutlined style={style} />,
    GitlabOutlined: <GitlabOutlined style={style} />,
    MediumOutlined: <MediumOutlined style={style} />,
    LinkedinOutlined: <LinkedinOutlined style={style} />,
    GooglePlusOutlined: <GooglePlusOutlined style={style} />,
    DropboxOutlined: <DropboxOutlined style={style} />,
    FacebookOutlined: <FacebookOutlined style={style} />,
    CodepenOutlined: <CodepenOutlined style={style} />,
    CodeSandboxOutlined: <CodeSandboxOutlined style={style} />,
    AmazonOutlined: <AmazonOutlined style={style} />,
    GoogleOutlined: <GoogleOutlined style={style} />,
    CodepenCircleOutlined: <CodepenCircleOutlined style={style} />,
    AlipayOutlined: <AlipayOutlined style={style} />,
    AntDesignOutlined: <AntDesignOutlined style={style} />,
    AntCloudOutlined: <AntCloudOutlined style={style} />,
    AliyunOutlined: <AliyunOutlined style={style} />,
    ZhihuOutlined: <ZhihuOutlined style={style} />,
    SlackOutlined: <SlackOutlined style={style} />,
    SlackSquareOutlined: <SlackSquareOutlined style={style} />,
    BehanceOutlined: <BehanceOutlined style={style} />,
    BehanceSquareOutlined: <BehanceSquareOutlined style={style} />,
    DribbbleOutlined: <DribbbleOutlined style={style} />,
    DribbbleSquareOutlined: <DribbbleSquareOutlined style={style} />,
    InstagramOutlined: <InstagramOutlined style={style} />,
    YuqueOutlined: <YuqueOutlined style={style} />,
    AlibabaOutlined: <AlibabaOutlined style={style} />,
    YahooOutlined: <YahooOutlined style={style} />,
    RedditOutlined: <RedditOutlined style={style} />,
    SketchOutlined: <SketchOutlined style={style} />,

    AreaChartOutlined: <AreaChartOutlined style={style} />,
    PieChartOutlined: <PieChartOutlined style={style} />,
    BarChartOutlined: <BarChartOutlined style={style} />,
    DotChartOutlined: <DotChartOutlined style={style} />,
    LineChartOutlined: <LineChartOutlined style={style} />,
    RadarChartOutlined: <RadarChartOutlined style={style} />,
    HeatMapOutlined: <HeatMapOutlined style={style} />,
    FallOutlined: <FallOutlined style={style} />,
    RiseOutlined: <RiseOutlined style={style} />,
    StockOutlined: <StockOutlined style={style} />,
    BoxPlotOutlined: <BoxPlotOutlined style={style} />,
    FundOutlined: <FundOutlined style={style} />,
    SlidersOutlined: <SlidersOutlined style={style} />,
    

    EditOutlined: <EditOutlined style={style} />,
    FormOutlined: <FormOutlined style={style} />,
    CopyOutlined: <CopyOutlined style={style} />,
    ScissorOutlined: <ScissorOutlined style={style} />,
    DeleteOutlined: <DeleteOutlined style={style} />,
    SnippetsOutlined: <SnippetsOutlined style={style} />,
    DiffOutlined: <DiffOutlined style={style} />,
    HighlightOutlined: <HighlightOutlined style={style} />,
    AlignCenterOutlined: <AlignCenterOutlined style={style} />,
    AlignLeftOutlined: <AlignLeftOutlined style={style} />,
    AlignRightOutlined: <AlignRightOutlined style={style} />,
    BgColorsOutlined: <BgColorsOutlined style={style} />,
    BoldOutlined: <BoldOutlined style={style} />,
    ItalicOutlined: <ItalicOutlined style={style} />,
    UnderlineOutlined: <UnderlineOutlined style={style} />,
    StrikethroughOutlined: <StrikethroughOutlined style={style} />,
    RedoOutlined: <RedoOutlined style={style} />,
    UndoOutlined: <UndoOutlined style={style} />,
    ZoomInOutlined: <ZoomInOutlined style={style} />,
    ZoomOutOutlined: <ZoomOutOutlined style={style} />,
    FontColorsOutlined: <FontColorsOutlined style={style} />,
    FontSizeOutlined: <FontSizeOutlined style={style} />,
    LineHeightOutlined: <LineHeightOutlined style={style} />,
    DashOutlined: <DashOutlined style={style} />,
    SmallDashOutlined: <SmallDashOutlined style={style} />,
    SortAscendingOutlined: <SortAscendingOutlined style={style} />,
    SortDescendingOutlined: <SortDescendingOutlined style={style} />,
    DragOutlined: <DragOutlined style={style} />,
    OrderedListOutlined: <OrderedListOutlined style={style} />,
    UnorderedListOutlined: <UnorderedListOutlined style={style} />,
    RadiusSettingOutlined: <RadiusSettingOutlined style={style} />,
    ColumnWidthOutlined: <ColumnWidthOutlined style={style} />,
    ColumnHeightOutlined: <ColumnHeightOutlined style={style} />,


    QuestionOutlined: <QuestionOutlined style={style} />,
    QuestionCircleOutlined: <QuestionCircleOutlined style={style} />,
    PlusOutlined: <PlusOutlined style={style} />,
    PlusCircleOutlined: <PlusCircleOutlined style={style} />,
    PauseOutlined: <PauseOutlined style={style} />,
    PauseCircleOutlined: <PauseCircleOutlined style={style} />,
    MinusOutlined: <MinusOutlined style={style} />,
    MinusCircleOutlined: <MinusCircleOutlined style={style} />,
    PlusSquareOutlined: <PlusSquareOutlined style={style} />,
    MinusSquareOutlined: <MinusSquareOutlined style={style} />,
    InfoOutlined: <InfoOutlined style={style} />,
    InfoCircleOutlined: <InfoCircleOutlined style={style} />,
    ExclamationOutlined: <ExclamationOutlined style={style} />,
    ExclamationCircleOutlined: <ExclamationCircleOutlined style={style} />,
    CloseOutlined: <CloseOutlined style={style} />,
    CloseCircleOutlined: <CloseCircleOutlined style={style} />,
    CloseSquareOutlined: <CloseSquareOutlined style={style} />,
    CheckOutlined: <CheckOutlined style={style} />,
    CheckCircleOutlined: <CheckCircleOutlined style={style} />,
    CheckSquareOutlined: <CheckSquareOutlined style={style} />,
    ClockCircleOutlined: <ClockCircleOutlined style={style} />,
    WarningOutlined: <WarningOutlined style={style} />,
    IssuesCloseOutlined: <IssuesCloseOutlined style={style} />,
    StopOutlined: <StopOutlined style={style} />,

    StepBackwardOutlined: <StepBackwardOutlined style={style} />, 
    StepForwardOutlined: <StepForwardOutlined style={style} />,
    FastBackwardOutlined: <FastBackwardOutlined style={style} />, 
    FastForwardOutlined: <FastForwardOutlined style={style} />,
    ShrinkOutlined: <ShrinkOutlined style={style} />, 
    ArrowsAltOutlined: <ArrowsAltOutlined style={style} />, 
    DownOutlined: <DownOutlined style={style} />, 
    UpOutlined: <UpOutlined style={style} />, 
    LeftOutlined: <LeftOutlined style={style} />,
    RightOutlined: <RightOutlined style={style} />, 
    CaretUpOutlined: <CaretUpOutlined style={style} />,
    CaretDownOutlined: <CaretDownOutlined style={style} />,
    CaretLeftOutlined: <CaretLeftOutlined style={style} />,
    CaretRightOutlined: <CaretRightOutlined style={style} />,
    UpCircleOutlined: <UpCircleOutlined style={style} />,
    DownCircleOutlined: <DownCircleOutlined style={style} />,
    LeftCircleOutlined: <LeftCircleOutlined style={style} />,
    RightCircleOutlined: <RightCircleOutlined style={style} />,
    DoubleRightOutlined: <DoubleRightOutlined style={style} />,
    DoubleLeftOutlined: <DoubleLeftOutlined style={style} />,
    VerticalLeftOutlined: <VerticalLeftOutlined style={style} />,
    VerticalRightOutlined: <VerticalRightOutlined style={style} />,
    VerticalAlignTopOutlined: <VerticalAlignTopOutlined/>,
    VerticalAlignMiddleOutlined: <VerticalAlignMiddleOutlined style={style} />,
    VerticalAlignBottomOutlined: <VerticalAlignBottomOutlined style={style} />,
    ForwardOutlined: <ForwardOutlined style={style} />,
    BackwardOutlined: <BackwardOutlined style={style} />, 
    RollbackOutlined: <RollbackOutlined style={style} />, 
    EnterOutlined: <EnterOutlined style={style} />,
    RetweetOutlined: <RetweetOutlined style={style} />,
    SwapOutlined: <SwapOutlined style={style} />,
    SwapLeftOutlined: <SwapLeftOutlined style={style} />, 
    SwapRightOutlined: <SwapRightOutlined style={style} />,
    ArrowUpOutlined: <ArrowUpOutlined style={style} />,
    ArrowDownOutlined: <ArrowDownOutlined style={style} />,
    ArrowLeftOutlined: <ArrowLeftOutlined style={style} />, 
    ArrowRightOutlined: <ArrowRightOutlined style={style} />,
    PlayCircleOutlined: <PlayCircleOutlined style={style} />,
    UpSquareOutlined: <UpSquareOutlined style={style} />,
    DownSquareOutlined: <DownSquareOutlined style={style} />,
    LeftSquareOutlined: <LeftSquareOutlined style={style} />,
    RightSquareOutlined: <RightSquareOutlined style={style} />,
    LoginOutlined: <LoginOutlined style={style} />,
    LogoutOutlined: <LogoutOutlined style={style} />,
    MenuFoldOutlined: <MenuFoldOutlined style={style} />,
    MenuUnfoldOutlined: <MenuUnfoldOutlined style={style} />,
    BorderBottomOutlined: <BorderBottomOutlined style={style} />,
    BorderHorizontalOutlined: <BorderHorizontalOutlined style={style} />, 
    BorderInnerOutlined: <BorderInnerOutlined style={style} />,
    BorderOuterOutlined: <BorderOuterOutlined style={style} />,
    BorderLeftOutlined: <BorderLeftOutlined style={style} />,
    BorderRightOutlined: <BorderRightOutlined style={style} />,
    BorderTopOutlined: <BorderTopOutlined style={style} />,
    BorderVerticleOutlined: <BorderVerticleOutlined style={style} />,
    PicCenterOutlined: <PicCenterOutlined style={style} />,
    PicLeftOutlined: <PicLeftOutlined style={style} />,
    PicRightOutlined: <PicRightOutlined style={style} />,
    RadiusBottomleftOutlined: <RadiusBottomleftOutlined style={style} />,
    RadiusBottomrightOutlined: <RadiusBottomrightOutlined style={style} />,
    RadiusUpleftOutlined: <RadiusUpleftOutlined style={style} />,
    RadiusUprightOutlined: <RadiusUprightOutlined style={style} />,
    FullscreenOutlined: <FullscreenOutlined style={style} />,
    FullscreenExitOutlined: <FullscreenExitOutlined style={style} />,
  }
}

interface IExcIconsProps {
  name: string,
  style?: any,
}
function ExcIcons(props: IExcIconsProps) {
  const {name='SettingOutlined', style={}} = props

  return iconObj(style)[name]
}

export default ExcIcons



